
name: runner

# Were we can define the inputs that our action will accept
inputs:
  folder:
    required: true
  build_command: 
    required: false
    default: ''
  run_command:
    required: true

runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
    - name: Prepare
      shell: bash
      run: |
          mkdir /res
          mkdir /datasets
          cp datasets/* /datasets
          touch /res/output-${{ inputs.folder }}-${{ matrix.amount }}-${{ matrix.attempt }}.txt
          cd BST/${{ inputs.folder }}
    - name: Build
          shell: bash
          run: |
              ${{ inputs.build_command }}
    - name: Run
          shell: bash
          run: |
              ${{ inputs.run_command }} ${{ matrix.amount }} > /res/output-${{ inputs.folder }}-${{ matrix.amount }}-${{ matrix.attempt }}.txt
              cat /res/output-${{ inputs.folder }}-${{ matrix.amount }}-${{ matrix.attempt }}.txt
    - name: Upload Output
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: /res/output-${{ inputs.folder }}-${{ matrix.amount }}-${{ matrix.attempt }}.txt
