
name: runner

# Were we can define the inputs that our action will accept
inputs:
  folder:
    required: true
  build_command: 
    required: false
    default: ''
  run_command:
    required: true

runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
    - name: Compile and Run
      shell: bash
      run: |
          mkdir -p ${{ github.workspace }}/temp
          mkdir /datasets
          cp datasets/* /datasets
          cd BST/${{ inputs.folder }}
          ${{ inputs.build_command }}
          ${{ inputs.run_command }} ${{ matrix.amount }} >  ${{ var.GITHUB_WORKSPACE }}/temp/output-${{ inputs.folder }}-${{ matrix.amount }}-${{ matrix.attempt }}.txt
    - name: Upload Output
      uses: actions/upload-artifact@v3
      with:
        name: output-${{ inputs.folder }}-${{ matrix.amount }}.txt
        path: ${{ var.GITHUB_WORKSPACE }}/temp