name: test_lang

# Were we can define the inputs that our action will accept
inputs:
  folder:
    required: true
  install_requires:
    required: false
    default: ""
  build_command:
    required: false
    default: ""
  run_command:
    required: true
  lenght:
    required: true
  height:
    required: true

runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
    - name: Prepare
      shell: bash
      run: |
        mkdir /res
        mkdir /datasets
        cp datasets/* /datasets
        touch /res/output-${{ inputs.folder }}-${{ inputs.lenght }}.txt
    - name: Install requirements
      if: ${{ inputs.install_requires }}
      working-directory: ${{ github.workspace }}/BST/${{ inputs.folder }}
      shell: bash
      run: |
        ${{ inputs.install_requires }}
    - name: Build
      if: ${{ inputs.build_command }}
      working-directory: ${{ github.workspace }}/BST/${{ inputs.folder }}
      shell: bash
      run: |
        ${{ inputs.build_command }}
    - name: Run
      working-directory: ${{ github.workspace }}/BST/${{ inputs.folder }}
      shell: bash
      run: |
        ${{ inputs.run_command }} ${{ inputs.lenght }} > /res/output-${{ inputs.folder }}-${{ inputs.lenght }}.txt
        cat /res/output-${{ inputs.folder }}-${{ inputs.lenght }}.txt
    - name: Set test_lang script permissions
      shell: bash
      run: chmod +x ./test_lang.sh
    - name: Run test_lang test
      shell: bash
      run: ./test_lang.sh /res/output-${{ inputs.folder }}-${{ inputs.lenght }}.txt
    - name: Set validate_results script permissions
      shell: bash
      run: chmod +x ./validate_results.sh
    - name: Run validate_results test
      shell: bash
      run: ./validate_results.sh /res/output-${{ inputs.folder }}-${{ inputs.lenght }}.txt ${{ inputs.lenght }} ${{ inputs.height }}
