# THIS FILE IS GENERATED AUTOMATICALLY. IF YOU WANT TO CHANGE THIS, CHANGE
# 'templates/action.yaml.j2' FILE

name: BST Workflow

on:
  workflow_dispatch:

jobs:

  
  julia:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount: [100, 1000, 10000, 100000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000]
        attempt: [1, 2, 3, 4, 5]
    container:
      image: julia:1.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run bst
        uses: "./.github/template/runner"
        with:
          folder: julia
          
          

          run_command: julia  main.jl

  
  lua:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount: [100, 1000, 10000, 100000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000]
        attempt: [1, 2, 3, 4, 5]
    container:
      image: nickblah/lua:5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run bst
        uses: "./.github/template/runner"
        with:
          folder: lua
          
          

          run_command: lua main.lua

  
  javascript:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount: [100, 1000, 10000, 100000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000]
        attempt: [1, 2, 3, 4, 5]
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run bst
        uses: "./.github/template/runner"
        with:
          folder: javascript
          
          

          run_command: node  main.js

  
  ruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount: [100, 1000, 10000, 100000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000]
        attempt: [1, 2, 3, 4, 5]
    container:
      image: ruby:3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run bst
        uses: "./.github/template/runner"
        with:
          folder: ruby
          
          

          run_command: ruby main.rb

  
  c:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount: [100, 1000, 10000, 100000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000]
        attempt: [1, 2, 3, 4, 5]
    container:
      image: gcc:12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run bst
        uses: "./.github/template/runner"
        with:
          folder: c
          
          build_command: gcc -std=c99 -o main.out main.c node.c tree.c

          run_command: ./main.out

  
  cs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount: [100, 1000, 10000, 100000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000]
        attempt: [1, 2, 3, 4, 5]
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run bst
        uses: "./.github/template/runner"
        with:
          folder: cs
          
          

          run_command: dotnet run

  
  python3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount: [100, 1000, 10000, 100000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000]
        attempt: [1, 2, 3, 4, 5]
    container:
      image: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run bst
        uses: "./.github/template/runner"
        with:
          folder: python3
          
          

          run_command: python main.py

  
  typescript:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount: [100, 1000, 10000, 100000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000]
        attempt: [1, 2, 3, 4, 5]
    container:
      image: mcr.microsoft.com/devcontainers/typescript-node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run bst
        uses: "./.github/template/runner"
        with:
          folder: typescript
          install_requires: npm i --save-dev @types/node
          build_command: tsc main.ts

          run_command: node main.js

  
  golang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount: [100, 1000, 10000, 100000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000]
        attempt: [1, 2, 3, 4, 5]
    container:
      image: golang:1.20.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run bst
        uses: "./.github/template/runner"
        with:
          folder: golang
          
          

          run_command: go run *.go

  
  rust:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount: [100, 1000, 10000, 100000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000]
        attempt: [1, 2, 3, 4, 5]
    container:
      image: rust:1.67
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run bst
        uses: "./.github/template/runner"
        with:
          folder: rust
          
          build_command: rustc main.rs

          run_command: ./main

  
  cpp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount: [100, 1000, 10000, 100000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000]
        attempt: [1, 2, 3, 4, 5]
    container:
      image: gcc:12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run bst
        uses: "./.github/template/runner"
        with:
          folder: cpp
          
          build_command: g++ -o main.out main.cpp tree.cpp node.cpp

          run_command: ./main.out

  
  powershell:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount: [100, 1000, 10000, 100000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000]
        attempt: [1, 2, 3, 4, 5]
    container:
      image: mcr.microsoft.com/powershell:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run bst
        uses: "./.github/template/runner"
        with:
          folder: powershell
          
          

          run_command: pwsh main.ps1

  
  java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount: [100, 1000, 10000, 100000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000]
        attempt: [1, 2, 3, 4, 5]
    container:
      image: ibmjava:8-sdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run bst
        uses: "./.github/template/runner"
        with:
          folder: java
          
          build_command: javac Main.java Node.java

          run_command: java -Xmx2g Main



  summary:
    needs: ['julia', 'lua', 'javascript', 'ruby', 'c', 'cs', 'python3', 'typescript', 'golang', 'rust', 'cpp', 'powershell', 'java']

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Output
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/temp
      - name: Install dependencies
        run: |
          python -m pip install matplotlib docker
      - name: Generate Summary
        run: |
          ls ${{ github.workspace }}/temp/results
          python pipeline_analysis.py ${{ github.workspace }}/temp/results
        working-directory: ${{ github.workspace }}
      - name: Commit new results
        run: |
          git add results/*
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'Upload new results'
      - name: Upload results.json
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          directory: .
