# THIS FILE IS GENERATED AUTOMATICALLY. IF YOU WANT TO CHANGE THIS, CHANGE
# 'templates/test_lang.yaml.j2' FILE

name: Test lang

on:
  pull_request:
    branches: [ master ]

jobs:

  
  c++:
    runs-on: ubuntu-latest
    container:
      image: gcc:12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test bst
        uses: "./.github/template/test_lang"
        with:
          folder: c++
          build_command: g++ -o main.out main.cpp tree.cpp node.cpp
          run_command: ./main.out
  
  rust:
    runs-on: ubuntu-latest
    container:
      image: rust:1.67
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test bst
        uses: "./.github/template/test_lang"
        with:
          folder: rust
          build_command: rustc main.rs
          run_command: ./main
  
  python3:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test bst
        uses: "./.github/template/test_lang"
        with:
          folder: python3
          build_command: 
          run_command: python main.py
  
  cs:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test bst
        uses: "./.github/template/test_lang"
        with:
          folder: cs
          build_command: 
          run_command: dotnet run
  
  c:
    runs-on: ubuntu-latest
    container:
      image: gcc:12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test bst
        uses: "./.github/template/test_lang"
        with:
          folder: c
          build_command: g++ -std=c99 -o main.out main.c node.c tree.c
          run_command: ./main.out
  
  lua:
    runs-on: ubuntu-latest
    container:
      image: nickblah/lua:5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test bst
        uses: "./.github/template/test_lang"
        with:
          folder: lua
          build_command: 
          run_command: lua main.lua
  
  golang:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test bst
        uses: "./.github/template/test_lang"
        with:
          folder: golang
          build_command: 
          run_command: go run *.go
